name: "ADLS connectivity test"
      
on:
  workflow_dispatch:
    inputs:
      storage:
        description: 'Please enter the storage account name' 
        required: true
        type: string

jobs:
  test-tcp-connection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read        

      - name: Launch a connectivity test from gha private runners towards the storage account ports 443
        shell: pwsh
        run: |
          Test-NetConnection -ComputerName ${{ inputs.storage }}.blob.core.windows.net -Port 443
          Test-NetConnection -ComputerName ${{ inputs.storage }}.dfs.core.windows.net -Port 443